### ISSUE TITLE
async_invoke_function

### ISSUE THREAD

**Issue by dudongbi** [aliyun/fc-python-sdk#25]
aliyun_fc2-2.0.3

Is `async_invoke_function` abandon?

I got error when using `async_invoke_function` while updating to fc2.
And found `headers={'x-fc-invocation-type':'Async'}` in `site-packages/fc2/client.py`.
Please update `README.rst`.

**Comment by rsonghuster** [comment]
yes, There is only one function interface `invoke_function`, distinguish between synchronous and asynchronous by x-fc-invocation-type parameters.
