### ISSUE TITLE
关于Client类_do_request实现的问题

### ISSUE THREAD

**Issue by jter** [aliyun/fc-python-sdk#33]
代码中其他的方法如invoke_function使用了_do_request作为发送请求的方法，当需要使用其他的发送http请求的方式的时候（如异步http，而不是用requests，或者改变发送请求的方式以提高性能）用户代码可以继承Client并实现自己的_do_request方法。但有个问题，就是在_do_request方法之外假定了_do_request方法返回的是一个requests中的Response实例，这样当用户想重载_do_request方法的时候，会发现到处都需要改，这里更好的做法是_do_request外部不要依赖特定的库的实例，数据以python的内置类型来返回，解除底层发送方法和其他方法的耦合。

一个小的设计问题带来了很大的使用成本，希望能够修改这个问题。

**Comment by rsonghuster** [comment]
您好，首先感谢您的反馈，对于_do_request的接口返回的requests中的Response实例，其实最后都是构造
```python
 r = self._do_request(method, path, headers, body=json.dumps(payload).encode('utf-8'))
return FcHttpResponse(r.headers, r.json()) 
```
理论上只要你重载的_do_reuqest返回的值是类型有headers属性和json方法就可以兼容吧

**Comment by jter** [comment]
hello，你说的实现方法确实**可以**实现兼容，但有几点：
1. 假定Response实例中的内容的地方不止这两个，见[这里](https://github.com/aliyun/fc-python-sdk/blob/3f459343752e0247140601f10357f44600e57afc/fc2/client.py#L603) 和[这里](https://github.com/aliyun/fc-python-sdk/blob/3f459343752e0247140601f10357f44600e57afc/fc2/client.py#L99)
2. 使用过程中，通常网络库返回一个自己的实例，想定制返回的实例只能在实例化之后的返回值中硬加，类似于：
``` python
   def _json():pass
   r.json = _json
```
且不说这样好不好，如果遇到同名的属性可能就非常的难受了。
3. 可以实现，但挺难受的。

**Comment by rsonghuster** [comment]
您好，我们之前_do_request的返回值使用requests中的Response对象就是因为这个容易使用，而且返回值中很多属性支持很多特性，比如r.content是返回的byte数据，r.text是解码后的text，r.json()直接把json string转为python 的类型等等。 您可以先fork一个，我们先看看其他的用户需求。 谢谢您的建议和反馈！給您一百个👍
