### ISSUE TITLE
异常中没有error message

### ISSUE THREAD

**Issue by rockuw** [aliyun/fc-python-sdk#5]
```py
client = fc.Client(
    endpoint='http://x.cn-hangzhou.fc.aliyuncs.com',
    accessKeyID='STS.CDAPSeNauw7um6H6jah1gx3hP',
    accessKeySecret='x',
    securityToken='')

try:
    resp = client.invoke_function('rockuw', 'hello-world')
except Exception as e:
    print 'error message: ', e.message # MESSAGE IS EMPTY!!!
```

**Comment by rsonghuster** [comment]
现在Python的最新版本已经是 python2.7.13/python3.6.2, 而 e.message 则是python2.5.x 的语法了。
推荐的写法是：
e.message 改为 e.args

https://stackoverflow.com/questions/13063212/deprecationwarning-baseexception-message-has-been-deprecated-as-of-python-2-6-e

**Comment by rsonghuster** [comment]
目前最新版本0.4 解决了异常中没有error message
try:
    resp = client.invoke_function('demo', 'world2')
except fc.FcError  as e: 
    print "error message: " , e.message
    print "err_code: " , e.err_code
    print "status_code: ", e.status_code
    print "request_id", e.request_id
